--TABLE CREATION

--drop table usr;
CREATE TABLE USR(
  user_id   INTEGER,
  username  VARCHAR(15),
  pword     VARCHAR(15)
);

--drop table car;
CREATE TABLE CAR(
  car_id INTEGER,
  make   VARCHAR(15),
  mdl    VARCHAR(15)
);

--drop table offer;
CREATE TABLE OFFER(
  offer_id INTEGER,
  usr  INTEGER,
  car   INTEGER
);

--KEYS AND TRIGGERS

ALTER TABLE USR
ADD(CONSTRAINT USERPK PRIMARY KEY(user_id));

ALTER TABLE CAR
ADD(CONSTRAINT CARPK PRIMARY KEY(car_id));

ALTER TABLE OFFER
ADD(CONSTRAINT OFFERPK PRIMARY KEY(offer_id));

CREATE SEQUENCE SEQ;
CREATE SEQUENCE SEQ2;
CREATE SEQUENCE SEQ3;

CREATE OR REPLACE TRIGGER USER_INSERT
  BEFORE INSERT ON USR
  FOR EACH ROW
BEGIN
  SELECT SEQ.NEXTVAL
  INTO :new.user_id
  FROM dual;
END;
/

CREATE OR REPLACE TRIGGER CAR_INSERT
  BEFORE INSERT ON CAR
  FOR EACH ROW
BEGIN
  SELECT SEQ2.NEXTVAL
  INTO :new.car_id
  FROM dual;
END;  
/

CREATE OR REPLACE TRIGGER OFFER_INSERT
  BEFORE INSERT ON OFFER
  FOR EACH ROW
BEGIN
  SELECT SEQ3.NEXTVAL
  INTO :new.offer_id
  FROM dual;
END;  
/

--FUNCTION DEFINITION

CREATE OR REPLACE PROCEDURE MAKE_USER
(USERNAME IN VARCHAR, PWORD IN VARCHAR)
AS
BEGIN
INSERT INTO USR VALUES(SEQ.NEXTVAL, USERNAME, PWORD);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE MAKE_CAR
(MAKE IN VARCHAR, MDL IN VARCHAR)
AS
BEGIN
INSERT INTO CAR VALUES(SEQ.NEXTVAL, MAKE, MDL);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE MAKE_OFFER
(USR IN INTEGER, CAR IN INTEGER)
AS
BEGIN
INSERT INTO OFFER VALUES(SEQ.NEXTVAL, USR, CAR);
COMMIT;
END;
/

--INITIAL DATA

EXECUTE MAKE_USER('MOHAMED', '123456');
EXECUTE MAKE_CAR('HONDA', 'CIVIC');

select * from usr;
select * from car;